

services:
  orderwebapi:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=OrderDB;User=sa;Password=DevStrong@123;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "DevStrong@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
